### ISSUE TITLE
string "amazontitles-3M" to "amazontitles-3m" in datasets.py

### ISSUE THREAD

**Issue by xiaohan2012** [mwydmuch/napkinXC#19]
Hi,

the following code is giving an error:

```python
from napkinxc.datasets import load_dataset

_ = load_dataset('AmazonTitles-3M', 'train')
```

```
ValueError: Dataset AmazonTitles-3M is not available
```

It should be easy to fix: just change the string `amazontitles-3M` to `amazontitles-3m` in the file `python/napkinxc/datasets.py`

**Comment by mwydmuch** [comment]
Thank you @xiaohan2012 for noticing this typo!
