### ISSUE TITLE
a possible bug during kmeans initialization

### ISSUE THREAD

**Issue by xiaohan2012** [mwydmuch/napkinXC#24]
Hi,

During kmeans initialization, the randomly generated row index can produce segfault.

https://github.com/mwydmuch/napkinXC/blob/6783031fc3ffe769092dc63292bb7f8857b73967/src/models/kmeans.cpp#L54

https://github.com/mwydmuch/napkinXC/blob/6783031fc3ffe769092dc63292bb7f8857b73967/src/models/kmeans.cpp#L56
I suppose it should be:

```c++
 std::uniform_int_distribution<int> dist(0, points - 1); 
```

Regards,
Han

**Comment by mwydmuch** [comment]
Hi @xiaohan2012, you are right, many thanks for reporting the bug! I've fixed it.
